version: '3'

services:

  full-teaching-mysql-TJobM:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=full_teaching

  full-teaching-TJobM-openvidu-server-kms:
    image: openvidu/openvidu-server-kms:2.3.0
    ports:
      - 4454:80
    environment:
      - openvidu.secret=MY_SECRET
      - openvidu.publicurl=docker

  full-teaching-TJobM:
    image: codeurjc/full-teaching:2.3.0
    depends_on:
      - full-teaching-mysql-TJobM
      - full-teaching-TJobM-openvidu-server-kms
    ports:
      - 5013:5001
    environment:
      - WAIT_HOSTS=full-teaching-mysql-TJobM:3306
      - WAIT_HOSTS_TIMEOUT=60
      - MYSQL_PORT_3306_TCP_ADDR=full-teaching-mysql-TJobM
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_ENV_MYSQL_DATABASE=full_teaching
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_PASSWORD=pass
      - server.port=5001
      - openvidu.url=https://full-teaching-TJobM-openvidu-server-kms:4454
      - openvidu.secret=MY_SECRET
networks:
  fullteaching-TJobM:
    driver: bridge
