#!/bin/bash

echo "Reiniciando elastest.Eliminando los contenedores"

docker rm $(docker ps -a -q)

echo "Reiniciando elastest.Eliminando todas las imagenes"

docker rmi $(docker images -q)

docker run --rm -v ~/.elastest:/data -v /var/run/docker.sock:/var/run/docker.sock elastest/platform start